use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};
use zdtwalk_dts::{
    format_property_value, serialize, DeviceTree, IncludeKind, OutputFormat, Resolver,
    SerializerConfig,
};

// ---------------------------------------------------------------------------
// CLI definition
// ---------------------------------------------------------------------------

#[derive(Parser)]
#[command(name = "zdtwalk")]
#[command(about = "Device Tree Source (.dts/.dtsi) analyser and converter")]
#[command(version)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Parse and print a summary of a DTS/DTSI file.
    Analyze {
        /// Input file path.
        input: PathBuf,

        /// Additional include search directories.
        #[arg(short = 'I', long = "include")]
        include_paths: Vec<PathBuf>,

        /// Resolve includes recursively before analysing.
        #[arg(long)]
        resolve: bool,
    },

    /// Convert a DTS/DTSI file to another format.
    Convert {
        /// Input file path.
        input: PathBuf,

        /// Output file path (prints to stdout when omitted).
        #[arg(short, long)]
        output: Option<PathBuf>,

        /// Output format.
        #[arg(short, long, default_value = "overlay")]
        format: FormatArg,

        /// Additional include search directories.
        #[arg(short = 'I', long = "include")]
        include_paths: Vec<PathBuf>,

        /// Resolve includes recursively before converting.
        #[arg(long)]
        resolve: bool,

        /// Sort properties alphabetically.
        #[arg(long)]
        sort_properties: bool,

        /// Sort child nodes alphabetically.
        #[arg(long)]
        sort_nodes: bool,

        /// Use N spaces for indentation instead of tabs.
        #[arg(long)]
        spaces: Option<usize>,
    },
}

#[derive(Clone, ValueEnum)]
enum FormatArg {
    Dts,
    Dtsi,
    Overlay,
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

fn main() {
    let cli = Cli::parse();

    if let Err(e) = run(cli) {
        eprintln!("error: {e}");
        std::process::exit(1);
    }
}

fn run(cli: Cli) -> Result<(), zdtwalk_dts::Error> {
    match cli.command {
        Commands::Analyze {
            input,
            include_paths,
            resolve,
        } => {
            let tree = load_tree(&input, &include_paths, resolve)?;
            print_analysis(&tree);
        }

        Commands::Convert {
            input,
            output,
            format,
            include_paths,
            resolve,
            sort_properties,
            sort_nodes,
            spaces,
        } => {
            let tree = load_tree(&input, &include_paths, resolve)?;

            let config = SerializerConfig {
                indent: match spaces {
                    Some(n) => " ".repeat(n),
                    None => "\t".to_string(),
                },
                header_comment: Some(
                    "This file was generated by zdtwalk.\nDo not edit manually.".to_string(),
                ),
                output_format: match format {
                    FormatArg::Dts => OutputFormat::Dts,
                    FormatArg::Dtsi => OutputFormat::Dtsi,
                    FormatArg::Overlay => OutputFormat::Overlay,
                },
                sort_properties,
                sort_nodes,
                include_version: true,
            };

            let result = serialize(&tree, &config);

            match output {
                Some(path) => std::fs::write(&path, &result)?,
                None => print!("{}", result),
            }
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn load_tree(
    input: &PathBuf,
    include_paths: &[PathBuf],
    resolve: bool,
) -> Result<DeviceTree, zdtwalk_dts::Error> {
    if resolve {
        let mut resolver = Resolver::new();
        for p in include_paths {
            resolver.add_search_path(p);
        }
        resolver.resolve_file(input)
    } else {
        let content = std::fs::read_to_string(input)?;
        Ok(zdtwalk_dts::parse_dts(&content)?)
    }
}

fn print_analysis(tree: &DeviceTree) {
    println!("=== Device Tree Analysis ===\n");

    if let Some(version) = &tree.version {
        println!("Version: {version}");
    }

    if tree.is_plugin {
        println!("Type:    plugin / overlay");
    }

    // includes
    if !tree.includes.is_empty() {
        println!("\nIncludes:");
        for inc in &tree.includes {
            let kind = match inc.kind {
                IncludeKind::CPreprocessor => "#include",
                IncludeKind::DtsInclude => "/include/",
            };
            println!("  {kind} \"{}\"", inc.path);
        }
    }

    // memory reservations
    if !tree.memory_reservations.is_empty() {
        println!("\nMemory Reservations:");
        for mr in &tree.memory_reservations {
            println!(
                "  {:#x} – {:#x} (size {:#x})",
                mr.address,
                mr.address.wrapping_add(mr.size),
                mr.size
            );
        }
    }

    // node tree
    if let Some(root) = &tree.root {
        println!("\nNode Tree:");
        print_node(root, "/", 0);
    }

    // reference overrides
    if !tree.reference_nodes.is_empty() {
        println!("\nReference Overrides:");
        for rn in &tree.reference_nodes {
            println!(
                "  {} ({} properties, {} children)",
                rn.reference,
                rn.node.properties.len(),
                rn.node.children.len(),
            );
        }
    }

    // statistics
    if let Some(root) = &tree.root {
        let (mut nodes, mut props, mut labels) = (0usize, 0usize, 0usize);
        root.walk(
            &mut |node, _depth| {
                nodes += 1;
                props += node.properties.len();
                labels += node.labels.len();
            },
            0,
        );

        println!("\nStatistics:");
        println!("  Nodes:               {nodes}");
        println!("  Properties:          {props}");
        println!("  Labels:              {labels}");
        println!(
            "  Reference overrides: {}",
            tree.reference_nodes.len()
        );
    }
}

fn print_node(node: &zdtwalk_dts::Node, display_name: &str, depth: usize) {
    let indent = "  ".repeat(depth);
    let label_str = if node.labels.is_empty() {
        String::new()
    } else {
        format!("  (labels: {})", node.labels.join(", "))
    };

    println!("{indent}{display_name}{label_str}");

    for prop in &node.properties {
        let val_str = match &prop.value {
            Some(v) => format!(" = {}", format_property_value(v)),
            None => String::new(),
        };
        println!("{indent}  [prop] {}{val_str}", prop.name);
    }

    for child in &node.children {
        print_node(child, &child.full_name(), depth + 1);
    }
}
