use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};

mod dts;
mod west;

use dts::{
    format_property_value, serialize, DeviceTree, IncludeKind, OutputFormat, Resolver,
    SerializerConfig,
};
use west::DtsSource;

// ---------------------------------------------------------------------------
// CLI definition
// ---------------------------------------------------------------------------

#[derive(Parser)]
#[command(name = "zdtwalk")]
#[command(about = "Device Tree Source (.dts/.dtsi) analyser and converter")]
#[command(version)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Parse and print a summary of a DTS/DTSI file.
    Analyze {
        /// Input file path.
        input: PathBuf,

        /// Additional include search directories.
        #[arg(short = 'I', long = "include")]
        include_paths: Vec<PathBuf>,

        /// Resolve includes recursively before analysing.
        #[arg(long)]
        resolve: bool,
    },

    /// Fetch DTS files from remote HAL repositories defined in west.yml.
    FetchHals {
        /// Re-fetch even if already cached.
        #[arg(long)]
        force: bool,

        /// Only use local and cached sources; do not fetch from remote.
        #[arg(long)]
        offline: bool,
    },

    /// Convert a DTS/DTSI file to another format.
    Convert {
        /// Input file path.
        input: PathBuf,

        /// Output file path (prints to stdout when omitted).
        #[arg(short, long)]
        output: Option<PathBuf>,

        /// Output format.
        #[arg(short, long, default_value = "overlay")]
        format: FormatArg,

        /// Additional include search directories.
        #[arg(short = 'I', long = "include")]
        include_paths: Vec<PathBuf>,

        /// Resolve includes recursively before converting.
        #[arg(long)]
        resolve: bool,

        /// Sort properties alphabetically.
        #[arg(long)]
        sort_properties: bool,

        /// Sort child nodes alphabetically.
        #[arg(long)]
        sort_nodes: bool,

        /// Use N spaces for indentation instead of tabs.
        #[arg(long)]
        spaces: Option<usize>,
    },
}

#[derive(Clone, ValueEnum)]
enum FormatArg {
    Dts,
    Dtsi,
    Overlay,
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

fn main() {
    let cli = Cli::parse();

    if let Err(e) = run(cli) {
        eprintln!("error: {e}");
        std::process::exit(1);
    }
}

fn run(cli: Cli) -> Result<(), dts::Error> {
    match cli.command {
        Commands::FetchHals { force, offline } => {
            run_fetch_hals(force, offline)?;
        }

        Commands::Analyze {
            input,
            include_paths,
            resolve,
        } => {
            let tree = load_tree(&input, &include_paths, resolve)?;
            print_analysis(&tree);
        }

        Commands::Convert {
            input,
            output,
            format,
            include_paths,
            resolve,
            sort_properties,
            sort_nodes,
            spaces,
        } => {
            let tree = load_tree(&input, &include_paths, resolve)?;

            let config = SerializerConfig {
                indent: match spaces {
                    Some(n) => " ".repeat(n),
                    None => "\t".to_string(),
                },
                header_comment: Some(
                    "This file was generated by zdtwalk.\nDo not edit manually.".to_string(),
                ),
                output_format: match format {
                    FormatArg::Dts => OutputFormat::Dts,
                    FormatArg::Dtsi => OutputFormat::Dtsi,
                    FormatArg::Overlay => OutputFormat::Overlay,
                },
                sort_properties,
                sort_nodes,
                include_version: true,
            };

            let result = serialize(&tree, &config);

            match output {
                Some(path) => std::fs::write(&path, &result)?,
                None => print!("{}", result),
            }
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn load_tree(
    input: &PathBuf,
    include_paths: &[PathBuf],
    resolve: bool,
) -> Result<DeviceTree, dts::Error> {
    if resolve {
        let mut resolver = Resolver::new();
        for p in include_paths {
            resolver.add_search_path(p);
        }
        resolver.resolve_file(input)
    } else {
        let content = std::fs::read_to_string(input)?;
        Ok(dts::parse_dts(&content)?)
    }
}

fn run_fetch_hals(force: bool, offline: bool) -> Result<(), dts::Error> {
    let cwd = std::env::current_dir()?;
    eprintln!("Searching for Zephyr workspace from {}", cwd.display());

    let workspace = west::find_workspace(&cwd)?;
    eprintln!(
        "Found workspace at {}",
        workspace.workspace_root.display()
    );

    let sdk_version = west::get_sdk_version(&workspace.zephyr_dir)?;
    eprintln!("SDK version: {sdk_version}");

    if offline {
        eprintln!("Offline mode: only using local and cached sources.");
    }

    let manifest = west::parse_west_manifest(&workspace.west_yml_path)?;
    let hal_projects = manifest.manifest.hal_projects();
    eprintln!("Found {} HAL projects in manifest.\n", hal_projects.len());

    let results = if offline {
        let mut results = Vec::new();
        for project in &hal_projects {
            eprint!("  {:<30} ", project.name);

            let local_dts = workspace
                .workspace_root
                .join(project.local_path())
                .join("dts");
            if local_dts.is_dir() {
                eprintln!("local  {}", local_dts.display());
                results.push(west::HalDtsEntry {
                    project_name: project.name.clone(),
                    path: Some(local_dts),
                    source: DtsSource::Local,
                });
                continue;
            }

            if !force {
                if west::cache::is_marked_no_dts(&sdk_version, &project.name)? {
                    eprintln!("no-dts (cached)");
                    results.push(west::HalDtsEntry {
                        project_name: project.name.clone(),
                        path: None,
                        source: DtsSource::NoDts,
                    });
                    continue;
                }
                if west::cache::is_cached(&sdk_version, &project.name)? {
                    let p = west::cache::dts_cache_path(&sdk_version, &project.name)?;
                    eprintln!("cached {}", p.display());
                    results.push(west::HalDtsEntry {
                        project_name: project.name.clone(),
                        path: Some(p),
                        source: DtsSource::Cached,
                    });
                    continue;
                }
            }

            eprintln!("skipped (offline)");
        }
        results
    } else {
        let results = west::fetch::fetch_all_hal_dts(&workspace, force)?;
        for entry in &results {
            eprint!("  {:<30} ", entry.project_name);
            match &entry.source {
                DtsSource::Local => {
                    eprintln!("local  {}", entry.path.as_ref().unwrap().display());
                }
                DtsSource::Cached => {
                    eprintln!("cached {}", entry.path.as_ref().unwrap().display());
                }
                DtsSource::Fetched => {
                    eprintln!("fetched {}", entry.path.as_ref().unwrap().display());
                }
                DtsSource::NoDts => {
                    eprintln!("no dts/ directory");
                }
            }
        }
        results
    };

    // Summary.
    let local_count = results.iter().filter(|e| e.source == DtsSource::Local).count();
    let cached_count = results.iter().filter(|e| e.source == DtsSource::Cached).count();
    let fetched_count = results.iter().filter(|e| e.source == DtsSource::Fetched).count();
    let no_dts_count = results.iter().filter(|e| e.source == DtsSource::NoDts).count();

    eprintln!("\nSummary:");
    eprintln!("  Local:   {local_count}");
    eprintln!("  Cached:  {cached_count}");
    eprintln!("  Fetched: {fetched_count}");
    eprintln!("  No DTS:  {no_dts_count}");

    Ok(())
}

fn print_analysis(tree: &DeviceTree) {
    println!("=== Device Tree Analysis ===\n");

    if let Some(version) = &tree.version {
        println!("Version: {version}");
    }

    if tree.is_plugin {
        println!("Type:    plugin / overlay");
    }

    // includes
    if !tree.includes.is_empty() {
        println!("\nIncludes:");
        for inc in &tree.includes {
            let kind = match inc.kind {
                IncludeKind::CPreprocessor => "#include",
                IncludeKind::DtsInclude => "/include/",
            };
            println!("  {kind} \"{}\"", inc.path);
        }
    }

    // memory reservations
    if !tree.memory_reservations.is_empty() {
        println!("\nMemory Reservations:");
        for mr in &tree.memory_reservations {
            println!(
                "  {:#x} – {:#x} (size {:#x})",
                mr.address,
                mr.address.wrapping_add(mr.size),
                mr.size
            );
        }
    }

    // node tree
    if let Some(root) = &tree.root {
        println!("\nNode Tree:");
        print_node(root, "/", 0);
    }

    // reference overrides
    if !tree.reference_nodes.is_empty() {
        println!("\nReference Overrides:");
        for rn in &tree.reference_nodes {
            println!(
                "  {} ({} properties, {} children)",
                rn.reference,
                rn.node.properties.len(),
                rn.node.children.len(),
            );
        }
    }

    // statistics
    if let Some(root) = &tree.root {
        let (mut nodes, mut props, mut labels) = (0usize, 0usize, 0usize);
        root.walk(
            &mut |node, _depth| {
                nodes += 1;
                props += node.properties.len();
                labels += node.labels.len();
            },
            0,
        );

        println!("\nStatistics:");
        println!("  Nodes:               {nodes}");
        println!("  Properties:          {props}");
        println!("  Labels:              {labels}");
        println!(
            "  Reference overrides: {}",
            tree.reference_nodes.len()
        );
    }
}

fn print_node(node: &dts::Node, display_name: &str, depth: usize) {
    let indent = "  ".repeat(depth);
    let label_str = if node.labels.is_empty() {
        String::new()
    } else {
        format!("  (labels: {})", node.labels.join(", "))
    };

    println!("{indent}{display_name}{label_str}");

    for prop in &node.properties {
        let val_str = match &prop.value {
            Some(v) => format!(" = {}", format_property_value(v)),
            None => String::new(),
        };
        println!("{indent}  [prop] {}{val_str}", prop.name);
    }

    for child in &node.children {
        print_node(child, &child.full_name(), depth + 1);
    }
}
